### ISSUE TITLE
stable release version?

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/go-ssb#135]
hi, i was wondering if there's a stable release version i should be using?

i keep running into errors ( #134 #81 #124 ), so was wondering if there's a specific version (commit) i should be using that's most stable. i don't see any recent tags or releases, but would def appreciate those if a maintainer was keen.

thanks! :purple_heart:

**Comment by cryptix** [comment]
I tried very hard to get something semi-stable as the NGI Project was wrapping up but there was a lot of rush and things might have slipped through the cracks...

Not sure where to put this PSA but against all hopes I'm really not in the mind-space to work on code after hours with my new day job and the pandemic really doesn't help either. In my free time I'm trying very hard to stay away from code related things and go-ssb is one of the many things that's suffering from this.

**Comment by decentral1se** [comment]
I'm gonna close this off as resolving it is part of tackling a whole lot of other issues. The README / FAQ make a lot of effort to alert folks that this is alpha software, so I hope it is clear enough without having this issue pinned. Trying to garden / scope issues down to specific fixes etc. Please lemme know if you think otherwise.
