### ISSUE TITLE
is go-ssb data store compatibile with oasis or other ssb clients?

### ISSUE THREAD

**Issue by mhfowler** [ssbc/go-ssb#80]
in the past with debugging the node ssb server, 
I would use oasis to take a look at what posts I could see, 
make posts, 
see my profile, 
by pointing oasis to use the same ~/.ssb folder as the pub I was using 

is this possible with go-ssb or definitely out of scope?

not a big deal if not possible, but just wondering

or alternatively, would be nice to create some documentation on the best way to test that things are working, 
and I'd be happy to help with this

**Comment by mhfowler** [comment]
separate from using a client,
I was able to verify that things are basically working, 

by running a go-sbot on my laptop, and on the raspberry pi, 
following each other using the public keys, 
then using `sbotcli publish`, `sobtcli connect`, and `sbotcli log`
to verify that messages are being exchanged 

if you agree this is a good 'basic test' 
I could make a mini documentation about this, 
"setting up go-ssb for simple minds" (this directed at myself)

**Comment by cryptix** [comment]
Hmmm sadly a hard no on re-using the folder with flumedb software directly.

What I _do_ have however is [this soft-fork of oasis](https://git.sr.ht/~cryptix/ssb-oasis/refs) that works with the `.ssb-go/socket`, in general most of ssb-client software can talk to go-ssb since some of the muxrpc commands are there (like `status`, `replicate.upTo` and `createLogStream`). I need to double check if it still works since I didn't use it since I merged EBT and private groups, might have disabled or crippled something...


Not as user friendly but another thing that works today is using `sbotcli upto` which returns replicate.upto where each object is a feed and their length as currently stored in the bot,  or `sbotcli log` which is equivalent to `createLogStream` (all the messagesin the receive log). Warning: will spew lots of JSON when called without `--seq N --limit M`. Anther good one is `sbotcli call status`, where the `Root: X` is the number of entries/messages in the _receive log_. 

(ps: should have changed the name in `status` from Root to Received, like i did in the code a while back.)
